# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kulpet345/hw5/Shooter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kulpet345/hw5/Shooter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kulpet345/hw5/Shooter/CMakeFiles /home/kulpet345/hw5/Shooter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kulpet345/hw5/Shooter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named shooter

# Build rule for target.
shooter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shooter
.PHONY : shooter

# fast build rule for target.
shooter/fast:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/build
.PHONY : shooter/fast

bullet.o: bullet.cpp.o

.PHONY : bullet.o

# target to build an object file
bullet.cpp.o:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/bullet.cpp.o
.PHONY : bullet.cpp.o

bullet.i: bullet.cpp.i

.PHONY : bullet.i

# target to preprocess a source file
bullet.cpp.i:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/bullet.cpp.i
.PHONY : bullet.cpp.i

bullet.s: bullet.cpp.s

.PHONY : bullet.s

# target to generate assembly for a file
bullet.cpp.s:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/bullet.cpp.s
.PHONY : bullet.cpp.s

bullet_geom.o: bullet_geom.cpp.o

.PHONY : bullet_geom.o

# target to build an object file
bullet_geom.cpp.o:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/bullet_geom.cpp.o
.PHONY : bullet_geom.cpp.o

bullet_geom.i: bullet_geom.cpp.i

.PHONY : bullet_geom.i

# target to preprocess a source file
bullet_geom.cpp.i:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/bullet_geom.cpp.i
.PHONY : bullet_geom.cpp.i

bullet_geom.s: bullet_geom.cpp.s

.PHONY : bullet_geom.s

# target to generate assembly for a file
bullet_geom.cpp.s:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/bullet_geom.cpp.s
.PHONY : bullet_geom.cpp.s

camera.o: camera.cpp.o

.PHONY : camera.o

# target to build an object file
camera.cpp.o:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/camera.cpp.o
.PHONY : camera.cpp.o

camera.i: camera.cpp.i

.PHONY : camera.i

# target to preprocess a source file
camera.cpp.i:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/camera.cpp.i
.PHONY : camera.cpp.i

camera.s: camera.cpp.s

.PHONY : camera.s

# target to generate assembly for a file
camera.cpp.s:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/camera.cpp.s
.PHONY : camera.cpp.s

enemy.o: enemy.cpp.o

.PHONY : enemy.o

# target to build an object file
enemy.cpp.o:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/enemy.cpp.o
.PHONY : enemy.cpp.o

enemy.i: enemy.cpp.i

.PHONY : enemy.i

# target to preprocess a source file
enemy.cpp.i:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/enemy.cpp.i
.PHONY : enemy.cpp.i

enemy.s: enemy.cpp.s

.PHONY : enemy.s

# target to generate assembly for a file
enemy.cpp.s:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/enemy.cpp.s
.PHONY : enemy.cpp.s

gen.o: gen.cpp.o

.PHONY : gen.o

# target to build an object file
gen.cpp.o:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/gen.cpp.o
.PHONY : gen.cpp.o

gen.i: gen.cpp.i

.PHONY : gen.i

# target to preprocess a source file
gen.cpp.i:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/gen.cpp.i
.PHONY : gen.cpp.i

gen.s: gen.cpp.s

.PHONY : gen.s

# target to generate assembly for a file
gen.cpp.s:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/gen.cpp.s
.PHONY : gen.cpp.s

geometry.o: geometry.cpp.o

.PHONY : geometry.o

# target to build an object file
geometry.cpp.o:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/geometry.cpp.o
.PHONY : geometry.cpp.o

geometry.i: geometry.cpp.i

.PHONY : geometry.i

# target to preprocess a source file
geometry.cpp.i:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/geometry.cpp.i
.PHONY : geometry.cpp.i

geometry.s: geometry.cpp.s

.PHONY : geometry.s

# target to generate assembly for a file
geometry.cpp.s:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/geometry.cpp.s
.PHONY : geometry.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/main.cpp.s
.PHONY : main.cpp.s

objloader.o: objloader.cpp.o

.PHONY : objloader.o

# target to build an object file
objloader.cpp.o:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/objloader.cpp.o
.PHONY : objloader.cpp.o

objloader.i: objloader.cpp.i

.PHONY : objloader.i

# target to preprocess a source file
objloader.cpp.i:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/objloader.cpp.i
.PHONY : objloader.cpp.i

objloader.s: objloader.cpp.s

.PHONY : objloader.s

# target to generate assembly for a file
objloader.cpp.s:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/objloader.cpp.s
.PHONY : objloader.cpp.s

shader.o: shader.cpp.o

.PHONY : shader.o

# target to build an object file
shader.cpp.o:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/shader.cpp.o
.PHONY : shader.cpp.o

shader.i: shader.cpp.i

.PHONY : shader.i

# target to preprocess a source file
shader.cpp.i:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/shader.cpp.i
.PHONY : shader.cpp.i

shader.s: shader.cpp.s

.PHONY : shader.s

# target to generate assembly for a file
shader.cpp.s:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/shader.cpp.s
.PHONY : shader.cpp.s

text2D.o: text2D.cpp.o

.PHONY : text2D.o

# target to build an object file
text2D.cpp.o:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/text2D.cpp.o
.PHONY : text2D.cpp.o

text2D.i: text2D.cpp.i

.PHONY : text2D.i

# target to preprocess a source file
text2D.cpp.i:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/text2D.cpp.i
.PHONY : text2D.cpp.i

text2D.s: text2D.cpp.s

.PHONY : text2D.s

# target to generate assembly for a file
text2D.cpp.s:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/text2D.cpp.s
.PHONY : text2D.cpp.s

texture.o: texture.cpp.o

.PHONY : texture.o

# target to build an object file
texture.cpp.o:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/texture.cpp.o
.PHONY : texture.cpp.o

texture.i: texture.cpp.i

.PHONY : texture.i

# target to preprocess a source file
texture.cpp.i:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/texture.cpp.i
.PHONY : texture.cpp.i

texture.s: texture.cpp.s

.PHONY : texture.s

# target to generate assembly for a file
texture.cpp.s:
	$(MAKE) -f CMakeFiles/shooter.dir/build.make CMakeFiles/shooter.dir/texture.cpp.s
.PHONY : texture.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... shooter"
	@echo "... edit_cache"
	@echo "... bullet.o"
	@echo "... bullet.i"
	@echo "... bullet.s"
	@echo "... bullet_geom.o"
	@echo "... bullet_geom.i"
	@echo "... bullet_geom.s"
	@echo "... camera.o"
	@echo "... camera.i"
	@echo "... camera.s"
	@echo "... enemy.o"
	@echo "... enemy.i"
	@echo "... enemy.s"
	@echo "... gen.o"
	@echo "... gen.i"
	@echo "... gen.s"
	@echo "... geometry.o"
	@echo "... geometry.i"
	@echo "... geometry.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... objloader.o"
	@echo "... objloader.i"
	@echo "... objloader.s"
	@echo "... shader.o"
	@echo "... shader.i"
	@echo "... shader.s"
	@echo "... text2D.o"
	@echo "... text2D.i"
	@echo "... text2D.s"
	@echo "... texture.o"
	@echo "... texture.i"
	@echo "... texture.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

